spring:
  application:
    name: sys-web
  mvc:
    view:
      suffix: .html
adminPath: /a
dataPath: data
feign:
  hystrix:
    enabled: true  # 开启通过feign调用接口的异常捕获，进入fallback实现类
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 关闭超时报错
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000   # 设置超时时间（毫秒）