spring:
  application:
    name: sys-web
  # 配置中心配置--------开始
  cloud:
    config:
      name: exploit #文件前缀名称
      profile: config-dev # 服务环境名称 例如 {name}-{profile} = exploit-config.yml
      uri: http://127.0.0.1:8888
  # 配置中心配置---------结束
  mvc:
    view:
      suffix: .html
feign:
  hystrix:
    enabled: true  # 开启通过feign调用接口的异常捕获，进入fallback实现类
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 关闭超时报错
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000   # 设置超时时间（毫秒）