server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    # 配置中心配置--------开始
#    config:
#      name: exploit #文件前缀名称
#      profile: config-dev # 服务环境名称 例如 {name}-{profile} = exploit-config.yml
#      uri: http://127.0.0.1:8888
    # 配置中心配置---------结束
    gateway:
      routes:
      - id: sys-web
        # uri: lb://sys-web # uri: lb表示从注册中心订阅服务。（不知道为什么调用为空白页）
        uri: http://localhost:8080 # uri: lb表示从注册中心订阅服务。
        predicates:
        - Path=/a/**
#        filters:
#        - StripPrefix=1 #去前缀 去几层
      - id: sys-web
#        uri: lb://database-service（不知道为什么调用为空白页）
        uri: http://localhost:8081
        predicates:
        - Path=/data/**
#        filters:
#        - StripPrefix=1 #去前缀 去几层