server:
  port: 8081
spring:
  application:
    name: base-service
  # 配置中心配置--------开始
  cloud:
    config:
      name: exploit #文件前缀名称
      profile: config-dev # 服务环境名称 例如 {name}-{profile} = exploit-config.yml
      discovery:
        enabled: true # 是否启用服务发现
        service-id: config-server # 配置中心的服务id,即spring.application.name
      username: user
      password: password123
  # 配置中心配置---------结束
  datasource:
    name: test
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exploit?setUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: lijin123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true # 开启自动驼峰命名规则映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/